### ISSUE TITLE
mod dead

### ISSUE THREAD

**Issue by Maikli-Messes** [josesdlf/ExtinctionTalesMod#11]
why so dead? gulp!

**Comment by josesdlf** [comment]
⣀⣠⣤⣤⣤⣤⢤⣤⣄⣀⣀⣀⣀⡀⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠉⠹⣾⣿⣛⣿⣿⣞⣿⣛⣺⣻⢾⣾⣿⣿⣿⣶⣶⣶⣄⡀⠄⠄⠄
⠄⠄⠠⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣆⠄⠄
⠄⠄⠘⠛⠛⠛⠛⠋⠿⣷⣿⣿⡿⣿⢿⠟⠟⠟⠻⠻⣿⣿⣿⣿⡀⠄
⠄⢀⠄⠄⠄⠄⠄⠄⠄⠄⢛⣿⣁⠄⠄⠒⠂⠄⠄⣀⣰⣿⣿⣿⣿⡀
⠄⠉⠛⠺⢶⣷⡶⠃⠄⠄⠨⣿⣿⡇⠄⡺⣾⣾⣾⣿⣿⣿⣿⣽⣿⣿
⠄⠄⠄⠄⠄⠛⠁⠄⠄⠄⢀⣿⣿⣧⡀⠄⠹⣿⣿⣿⣿⣿⡿⣿⣻⣿
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠛⠟⠇⢀⢰⣿⣿⣿⣏⠉⢿⣽⢿⡏
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠠⠤⣤⣴⣾⣿⣿⣾⣿⣿⣦⠄⢹⡿⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠒⣳⣶⣤⣤⣄⣀⣀⡈⣀⢁⢁⢁⣈⣄⢐⠃⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⣰⣿⣛⣻⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡯⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⣬⣽⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⢘⣿⣿⣻⣛⣿⡿⣟⣻⣿⣿⣿⣿⡟⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠛⢛⢿⣿⣿⣿⣿⣿⣿⣷⡿⠁⠄⠄⠄
⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠉⠉⠉⠉⠈⠄⠄⠄⠄⠄⠄

**Comment by Maikli-Messes** [comment]
![image](https://user-images.githubusercontent.com/83659299/232673472-fa642a57-a388-4a3a-82f7-9854b81b25b7.png)

**Comment by TheEternalAce** [comment]
So dead pensive emoji

**Comment by Maikli-Messes** [comment]
![image](https://user-images.githubusercontent.com/83659299/232955966-1d6ae3fb-7aa6-479f-895f-f9e703cb010c.png)
i forgot to mention the amount of et references are in my mod
![image](https://user-images.githubusercontent.com/83659299/232956102-e39141fb-21eb-437e-9f41-863a09411efe.png)
![image](https://user-images.githubusercontent.com/83659299/232956177-c08f0df0-13ce-4e7b-a1af-5b770db0fab2.png)
![image](https://user-images.githubusercontent.com/83659299/232956331-5238a772-e27a-403a-964d-a87d643fa1fd.png)

**Comment by josesdlf** [comment]
Good memories

**Comment by Maikli-Messes** [comment]
![pixil-frame-0 (19)](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/39e6f76d-4e47-456b-98fe-06eb2f9478b3)
![pixil-frame-0 (15)](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/16460768-ad5e-4dd6-814c-8ef3c5b478cb)
![pixil-frame-0 (14)](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/364655d7-fbce-4655-932d-31bcff170c5b)
![pixil-frame-0 (13)](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/5990704e-89b8-4e68-a1f4-22d688512161)
i loved the concept of virium making drugs (torra th suggested them) and decided to just go wacky and wild with it
also man you can see how i improved so much over the last 2 years because old virium sucks

**Comment by nightlight00** [comment]
he returned

**Comment by TheEternalAce** [comment]
The

**Comment by Maikli-Messes** [comment]
![image](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/f82cb8eb-ca54-4e33-8620-1128032b8d7b)
this is truly a extinction level event
this is for tewst mod from torra th

**Comment by Maikli-Messes** [comment]
update: was burnt out on my mod and stopped for a couple months but now im back and im so motivated. i also ported the mod to 1.4.4. would post a image but im basically done referencing et stuff

**Comment by Maikli-Messes** [comment]
ok nvm about being done referencing et stuff here me out:
![image](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/8b41c712-3685-4b9d-972b-2f1994363b64)
![image](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/d7efcccc-01f4-4f43-ae5d-37c68df9ebcc)
![image](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/67dd9968-afeb-4d58-8dd6-720e73e8d5b5)

i serious love doing this i can finally plan out my concepts for et and theyre so good
its crazy seeing the glowup

**Comment by Maikli-Messes** [comment]
![image](https://github.com/Nyer00/ExtinctionTalesMod/assets/83659299/d8f6d064-a3ff-4f90-ab04-adb4d94c6a44)
this guy has been in medial rift for more than a year but i got around to revamping his ai a bit




cybord slim

**Comment by TheEternalAce** [comment]
Omg
